Create cluster without using a failed task
Currently a new cluster is created by using a try/rescue
operation which always fails for a new cluster, causing
a lot of confusion due to the failed task report.

This patch implements an improvement which tests the
cluster state and creates a new one if it is not ready
without requiring the task to fail.

As the cluster creation is a single task, it's merged
into the rabbitmq_cluster.yml task file.

As the tags are all the same, the tag is set in the
main task file instead of individually on all the tasks.

Change-Id: Iaa8e429cbd1c539d8242453c0490373c758dd9fe
(cherry picked from commit 3b897ad51551f47d3e11cf182c5ecfe14d3130af)

diff --git a/tasks/rabbitmq_cluster.yml b/tasks/rabbitmq_cluster.yml
--- a/tasks/rabbitmq_cluster.yml
+++ b/tasks/rabbitmq_cluster.yml
@@ -13,9 +13,23 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-- include: rabbitmq_cluster_create.yml
-  static: no
+- name: Get rabbitmq cluster name
+  shell: |
+    return_code=0
+    if ! rabbitmqctl cluster_status | grep -w '<<"{{ rabbitmq_cluster_name }}">>'; then
+      rabbitmqctl set_cluster_name {{ rabbitmq_cluster_name }}
+      return_code=2
+    fi
+    exit ${return_code}
   when: ansible_hostname == rabbitmq_primary_cluster_node
+  register: _set_cluster_name
+  changed_when: _set_cluster_name.rc == 2
+  failed_when: _set_cluster_name.rc not in [0, 2]
+  # We skip ansible lint testing for this task as it fails with
+  # ANSIBLE0014 Environment variables don't work as part of command
+  # which is nonsense.
+  tags:
+    - skip_ansible_lint
 
 - include: rabbitmq_cluster_join.yml
   static: no
